### ISSUE TITLE
Unable to reproduce the results of the paper, need some details. Please help this issue. 

### ISSUE THREAD

**Issue by TianheWu** [sunwei925/MC360IQA#3]
Hi, thanks for your great worl for OIQA task!
I am working on OIQA task now. When I reproduce MC360IQA with pure Python code, without matlab, I can not attain the results published on this paper.

Meanwhile, I found that using ResNet-34,50 ... what ever, the network even can not converge.

I want to know that, after generating the Cubemap from the ERP (six plane), the resolution of each plane? 512x512? , 224x224?

 Or any other resolution. We can not send the original resolution image into network, because it will cause too many RAM. Furthermore, to adapt the pre-trained weights, we may resize the image to a smaller resoution such as VGCN.

**Comment by sunwei925** [comment]
Hi TianheWu,

The resolution of the cubemap from the ERP image is 1024x1024. You can use the same code (equi2cubic/ConvertCVIQtoCubic.m) to obatain all trained cubemap images (544x180x6). In the training stage, the resolution of each cubemap is resize to 224x224. 

Hope this helps you!

**Comment by TianheWu** [comment]
Thanks!
